theme: jekyll-theme-clean-blog
baseurl: ""
url: "https://izumix77.github.io"
title: "Algorithmic Lifestyle"
description: "Exploring what it means to live a life shaped by code, intelligence, and intention."

author: "Izumix77"
email: ""
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
paginate: 5
paginate_path: "/posts/page:num/"